AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  thumbnail-rust

  Sample SAM Template for thumbnail-rust

Parameters:
  BucketName:
    Type: String
    Default: thumbnail-bucket-rust # Define unique name for the input bucket

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  ThumbnailsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  ThumbnailsBucketOutput:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-thumbs" #

  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda # More info about Cargo Lambda: https://github.com/cargo-lambda/cargo-lambda
    Properties:
      CodeUri: ./rust_app # Points to dir of Cargo.toml
      Handler: bootstrap # Do not change, as this is the default executable name produced by Cargo Lambda
      Runtime: provided.al2
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName
        - S3WritePolicy:
            BucketName: !Sub "${BucketName}-thumbs"
      Events:
        S3NewObjectEvent:
          Type: S3
          Properties:
            Bucket: !Ref ThumbnailsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".png"

  LambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt ThumbnailFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "s3.amazonaws.com"
      SourceArn: !GetAtt ThumbnailsBucket.Arn

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
